### ISSUE TITLE
Background image for the pages

### ISSUE THREAD

**Issue by karandhodi** [demisto/sane-reports#86]
Hi, is there a way to add a background image to the report pages or a background image to a specific section? Thanks !

**Comment by Bars92** [comment]
hey @karandhodi! in order to add background image you can use simple css on each section by using the `style` inside the `layout`

in the following example section:
```
  {
    "type": "text",
    "data": "This is left small green text.",
    "layout": {
      "rowPos": 2,
      "columnPos": 1,
      "style": {
        "backgroundImage": "url(https://images.freeimages.com/images/large-previews/b8d/irish-landscape-1393571.jpg)",
        "textAlign": "left",
        "display": "flex",
        "alignItems": "center",
        "padding": "20px",
        "fontSize": 12,
        "color": "#1f8f51"
      }
    }
  }
```
![image](https://user-images.githubusercontent.com/18641362/68421216-7f4a5c00-01a6-11ea-8388-57d16d30b364.png)

the css style is called [inline style](https://zhenyong.github.io/react/tips/inline-styles.html), that is used with react.

i will add this example to the test.json as a future reference as well

**Comment by karandhodi** [comment]
Thanks a lot for your help ! Really appreciate it :)
